/**
 * Public entry point for the Firebase layer.
 *
 * Application code should import from `@/lib/firebase` rather than reaching
 * into individual modules, so the internal file layout can change without
 * touching callers.
 */

export {
  FIREBASE_PROJECT_ID,
  dataSourceMode,
  firebaseClientConfig,
  firebaseUnavailableReason,
  getDb,
  getFirebaseApp,
  getFirebaseAuth,
  getFirebaseStorage,
  isBrowser,
  isEmulatorRequested,
  isFirebaseActive,
  isFirebaseConfigured,
  missingFirebaseKeys,
  resetFirebaseClientsForTests,
  type DataSourceMode,
  type FirebaseClientConfig,
} from "./config";

export {
  FirebaseBrowserOnlyError,
  FirebaseNotConfiguredError,
  changePassword,
  clearPhoneVerification,
  confirmPhoneOtp,
  getCurrentUser,
  linkEmailToUser,
  linkPhoneToUser,
  normalisePhoneE164,
  registerWithEmail,
  resetPassword,
  setDisplayName,
  signInWithEmail,
  signOut,
  startPhoneLink,
  startPhoneSignIn,
  subscribeToAuth,
  toUserCredentialResult,
  type UserCredentialResult,
} from "./auth";

export {
  COLLECTIONS,
  addUserCapability,
  approveRetailerApplication,
  claimDeliveryTask,
  createDeliveryTask,
  createOrder,
  createPayment,
  createUserProfile,
  ensureUserProfile,
  fetchAddress,
  fetchAddresses,
  fetchAllProducts,
  fetchAllShops,
  fetchAvailableTasks,
  fetchAvailableProductsByShop,
  fetchCategory,
  fetchCategories,
  fetchDeliveryTask,
  fetchOrder,
  fetchOrdersForCustomer,
  fetchOrdersForShop,
  fetchProduct,
  fetchProductsByShop,
  fetchProductsByCategory,
  fetchPaymentsForOrder,
  fetchRetailerApplication,
  fetchRetailerApplications,
  fetchShop,
  fetchShopByOwner,
  fetchShops,
  fetchShopsByCategory,
  fetchTasksForWorker,
  fetchUser,
  fetchUsersByCapability,
  refPath,
  removeAddress,
  removeProduct,
  removeUserCapability,
  rejectRetailerApplication,
  saveAddress,
  saveCategory,
  saveProduct,
  saveShop,
  submitRetailerApplication,
  setUserAccountStatus,
  stripUndefined,
  transitionOrder,
  updateAddress,
  updateDeliveryTask,
  updateOrder,
  updatePayment,
  updateProduct,
  updateShop,
  updateUserProfile,
  type CollectionName,
  type UserProfile,
  type SafeUserProfilePatch,
} from "./firestore";

export {
  FirebaseStorageUnavailableError,
  deleteProductImage,
  productImagePath,
  productImageRef,
  replaceProductImage,
  uploadProductImage,
} from "./storage";

export {
  connectAuth,
  connectFirestore,
  connectFirebaseEmulators,
  connectStorage,
} from "./emulator";
