/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as MapRouteImport } from './routes/map'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RetailerRouteImport } from './routes/retailer'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as RetailerDashboardRouteImport } from './routes/retailer.dashboard'
import { Route as RetailerInventoryRouteImport } from './routes/retailer.inventory'
import { Route as RetailerLoginRouteImport } from './routes/retailer.login'
import { Route as RetailerProfileRouteImport } from './routes/retailer.profile'
import { Route as RetailerShopRouteImport } from './routes/retailer.shop'
import { Route as ShopsShopIdRouteImport } from './routes/shops.$shopId'
import { Route as RetailerOrdersIndexRouteImport } from './routes/retailer.orders.index'
import { Route as RetailerOrdersOrderIdRouteImport } from './routes/retailer.orders.$orderId'
import { Route as RetailerProductsIndexRouteImport } from './routes/retailer.products.index'
import { Route as RetailerProductsNewRouteImport } from './routes/retailer.products.new'
import { Route as RetailerProductsProductIdEditRouteImport } from './routes/retailer.products.$productId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerRoute = RetailerRouteImport.update({
  id: '/retailer',
  path: '/retailer',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerDashboardRoute = RetailerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerInventoryRoute = RetailerInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerLoginRoute = RetailerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerProfileRoute = RetailerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerShopRoute = RetailerShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => RetailerRoute,
} as any)
const ShopsShopIdRoute = ShopsShopIdRouteImport.update({
  id: '/shops/$shopId',
  path: '/shops/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerOrdersIndexRoute = RetailerOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerOrdersOrderIdRoute = RetailerOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerProductsIndexRoute = RetailerProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerProductsNewRoute = RetailerProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerProductsProductIdEditRoute =
  RetailerProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => RetailerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/retailer': typeof RetailerRouteWithChildren
  '/search': typeof SearchRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/retailer/dashboard': typeof RetailerDashboardRoute
  '/retailer/inventory': typeof RetailerInventoryRoute
  '/retailer/login': typeof RetailerLoginRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer/shop': typeof RetailerShopRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/retailer/orders/$orderId': typeof RetailerOrdersOrderIdRoute
  '/retailer/products/new': typeof RetailerProductsNewRoute
  '/retailer/orders/': typeof RetailerOrdersIndexRoute
  '/retailer/products/': typeof RetailerProductsIndexRoute
  '/retailer/products/$productId/edit': typeof RetailerProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/retailer': typeof RetailerRouteWithChildren
  '/search': typeof SearchRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/retailer/dashboard': typeof RetailerDashboardRoute
  '/retailer/inventory': typeof RetailerInventoryRoute
  '/retailer/login': typeof RetailerLoginRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer/shop': typeof RetailerShopRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/orders': typeof OrdersIndexRoute
  '/retailer/orders/$orderId': typeof RetailerOrdersOrderIdRoute
  '/retailer/products/new': typeof RetailerProductsNewRoute
  '/retailer/orders': typeof RetailerOrdersIndexRoute
  '/retailer/products': typeof RetailerProductsIndexRoute
  '/retailer/products/$productId/edit': typeof RetailerProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/retailer': typeof RetailerRouteWithChildren
  '/search': typeof SearchRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/retailer/dashboard': typeof RetailerDashboardRoute
  '/retailer/inventory': typeof RetailerInventoryRoute
  '/retailer/login': typeof RetailerLoginRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer/shop': typeof RetailerShopRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/retailer/orders/$orderId': typeof RetailerOrdersOrderIdRoute
  '/retailer/products/new': typeof RetailerProductsNewRoute
  '/retailer/orders/': typeof RetailerOrdersIndexRoute
  '/retailer/products/': typeof RetailerProductsIndexRoute
  '/retailer/products/$productId/edit': typeof RetailerProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/map'
    | '/profile'
    | '/retailer'
    | '/search'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/retailer/dashboard'
    | '/retailer/inventory'
    | '/retailer/login'
    | '/retailer/profile'
    | '/retailer/shop'
    | '/shops/$shopId'
    | '/orders/'
    | '/retailer/orders/$orderId'
    | '/retailer/products/new'
    | '/retailer/orders/'
    | '/retailer/products/'
    | '/retailer/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/map'
    | '/profile'
    | '/retailer'
    | '/search'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/retailer/dashboard'
    | '/retailer/inventory'
    | '/retailer/login'
    | '/retailer/profile'
    | '/retailer/shop'
    | '/shops/$shopId'
    | '/orders'
    | '/retailer/orders/$orderId'
    | '/retailer/products/new'
    | '/retailer/orders'
    | '/retailer/products'
    | '/retailer/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/map'
    | '/profile'
    | '/retailer'
    | '/search'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/retailer/dashboard'
    | '/retailer/inventory'
    | '/retailer/login'
    | '/retailer/profile'
    | '/retailer/shop'
    | '/shops/$shopId'
    | '/orders/'
    | '/retailer/orders/$orderId'
    | '/retailer/products/new'
    | '/retailer/orders/'
    | '/retailer/products/'
    | '/retailer/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  RetailerRoute: typeof RetailerRouteWithChildren
  SearchRoute: typeof SearchRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ShopsShopIdRoute: typeof ShopsShopIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer': {
      id: '/retailer'
      path: '/retailer'
      fullPath: '/retailer'
      preLoaderRoute: typeof RetailerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer/dashboard': {
      id: '/retailer/dashboard'
      path: '/dashboard'
      fullPath: '/retailer/dashboard'
      preLoaderRoute: typeof RetailerDashboardRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/inventory': {
      id: '/retailer/inventory'
      path: '/inventory'
      fullPath: '/retailer/inventory'
      preLoaderRoute: typeof RetailerInventoryRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/login': {
      id: '/retailer/login'
      path: '/login'
      fullPath: '/retailer/login'
      preLoaderRoute: typeof RetailerLoginRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/profile': {
      id: '/retailer/profile'
      path: '/profile'
      fullPath: '/retailer/profile'
      preLoaderRoute: typeof RetailerProfileRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/shop': {
      id: '/retailer/shop'
      path: '/shop'
      fullPath: '/retailer/shop'
      preLoaderRoute: typeof RetailerShopRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/shops/$shopId': {
      id: '/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof ShopsShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer/orders/': {
      id: '/retailer/orders/'
      path: '/orders'
      fullPath: '/retailer/orders/'
      preLoaderRoute: typeof RetailerOrdersIndexRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/orders/$orderId': {
      id: '/retailer/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/retailer/orders/$orderId'
      preLoaderRoute: typeof RetailerOrdersOrderIdRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/products/': {
      id: '/retailer/products/'
      path: '/products'
      fullPath: '/retailer/products/'
      preLoaderRoute: typeof RetailerProductsIndexRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/products/new': {
      id: '/retailer/products/new'
      path: '/products/new'
      fullPath: '/retailer/products/new'
      preLoaderRoute: typeof RetailerProductsNewRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/products/$productId/edit': {
      id: '/retailer/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/retailer/products/$productId/edit'
      preLoaderRoute: typeof RetailerProductsProductIdEditRouteImport
      parentRoute: typeof RetailerRoute
    }
  }
}

interface RetailerRouteChildren {
  RetailerDashboardRoute: typeof RetailerDashboardRoute
  RetailerInventoryRoute: typeof RetailerInventoryRoute
  RetailerLoginRoute: typeof RetailerLoginRoute
  RetailerProfileRoute: typeof RetailerProfileRoute
  RetailerShopRoute: typeof RetailerShopRoute
  RetailerOrdersOrderIdRoute: typeof RetailerOrdersOrderIdRoute
  RetailerProductsNewRoute: typeof RetailerProductsNewRoute
  RetailerOrdersIndexRoute: typeof RetailerOrdersIndexRoute
  RetailerProductsIndexRoute: typeof RetailerProductsIndexRoute
  RetailerProductsProductIdEditRoute: typeof RetailerProductsProductIdEditRoute
}

const RetailerRouteChildren: RetailerRouteChildren = {
  RetailerDashboardRoute: RetailerDashboardRoute,
  RetailerInventoryRoute: RetailerInventoryRoute,
  RetailerLoginRoute: RetailerLoginRoute,
  RetailerProfileRoute: RetailerProfileRoute,
  RetailerShopRoute: RetailerShopRoute,
  RetailerOrdersOrderIdRoute: RetailerOrdersOrderIdRoute,
  RetailerProductsNewRoute: RetailerProductsNewRoute,
  RetailerOrdersIndexRoute: RetailerOrdersIndexRoute,
  RetailerProductsIndexRoute: RetailerProductsIndexRoute,
  RetailerProductsProductIdEditRoute: RetailerProductsProductIdEditRoute,
}

const RetailerRouteWithChildren = RetailerRoute._addFileChildren(
  RetailerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  RetailerRoute: RetailerRouteWithChildren,
  SearchRoute: SearchRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ShopsShopIdRoute: ShopsShopIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
