/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MapRouteImport } from './routes/map'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RetailerRouteImport } from './routes/retailer'
import { Route as RetailerApplicationRouteImport } from './routes/retailer-application'
import { Route as SearchRouteImport } from './routes/search'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDeliveryRouteImport } from './routes/admin.delivery'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMoreRouteImport } from './routes/admin.more'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminRetailerApplicationsRouteImport } from './routes/admin.retailer-applications'
import { Route as AdminRetailersRouteImport } from './routes/admin.retailers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as RetailerDashboardRouteImport } from './routes/retailer.dashboard'
import { Route as RetailerHelpRouteImport } from './routes/retailer.help'
import { Route as RetailerInventoryRouteImport } from './routes/retailer.inventory'
import { Route as RetailerLoginRouteImport } from './routes/retailer.login'
import { Route as RetailerMoreRouteImport } from './routes/retailer.more'
import { Route as RetailerProfileRouteImport } from './routes/retailer.profile'
import { Route as RetailerShopRouteImport } from './routes/retailer.shop'
import { Route as ShopsShopIdRouteImport } from './routes/shops.$shopId'
import { Route as WorkerDashboardRouteImport } from './routes/worker.dashboard'
import { Route as WorkerHelpRouteImport } from './routes/worker.help'
import { Route as WorkerLoginRouteImport } from './routes/worker.login'
import { Route as WorkerMoreRouteImport } from './routes/worker.more'
import { Route as WorkerProfileRouteImport } from './routes/worker.profile'
import { Route as AdminDeliveryTaskIdRouteImport } from './routes/admin.delivery.$taskId'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin.products.$productId'
import { Route as AdminRetailersRetailerIdRouteImport } from './routes/admin.retailers.$retailerId'
import { Route as AdminShopsShopIdRouteImport } from './routes/admin.shops.$shopId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as RetailerOrdersIndexRouteImport } from './routes/retailer.orders.index'
import { Route as RetailerOrdersOrderIdRouteImport } from './routes/retailer.orders.$orderId'
import { Route as RetailerProductsIndexRouteImport } from './routes/retailer.products.index'
import { Route as RetailerProductsNewRouteImport } from './routes/retailer.products.new'
import { Route as WorkerTasksIndexRouteImport } from './routes/worker.tasks.index'
import { Route as WorkerTasksTaskIdRouteImport } from './routes/worker.tasks.$taskId'
import { Route as RetailerProductsProductIdEditRouteImport } from './routes/retailer.products.$productId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerRoute = RetailerRouteImport.update({
  id: '/retailer',
  path: '/retailer',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerApplicationRoute = RetailerApplicationRouteImport.update({
  id: '/retailer-application',
  path: '/retailer-application',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoreRoute = AdminMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRetailerApplicationsRoute =
  AdminRetailerApplicationsRouteImport.update({
    id: '/retailer-applications',
    path: '/retailer-applications',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRetailersRoute = AdminRetailersRouteImport.update({
  id: '/retailers',
  path: '/retailers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerDashboardRoute = RetailerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerHelpRoute = RetailerHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerInventoryRoute = RetailerInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerLoginRoute = RetailerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerMoreRoute = RetailerMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerProfileRoute = RetailerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerShopRoute = RetailerShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => RetailerRoute,
} as any)
const ShopsShopIdRoute = ShopsShopIdRouteImport.update({
  id: '/shops/$shopId',
  path: '/shops/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerDashboardRoute = WorkerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerHelpRoute = WorkerHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerLoginRoute = WorkerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerMoreRoute = WorkerMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerProfileRoute = WorkerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkerRoute,
} as any)
const AdminDeliveryTaskIdRoute = AdminDeliveryTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AdminDeliveryRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminRetailersRetailerIdRoute =
  AdminRetailersRetailerIdRouteImport.update({
    id: '/$retailerId',
    path: '/$retailerId',
    getParentRoute: () => AdminRetailersRoute,
  } as any)
const AdminShopsShopIdRoute = AdminShopsShopIdRouteImport.update({
  id: '/$shopId',
  path: '/$shopId',
  getParentRoute: () => AdminShopsRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const RetailerOrdersIndexRoute = RetailerOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerOrdersOrderIdRoute = RetailerOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerProductsIndexRoute = RetailerProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerProductsNewRoute = RetailerProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => RetailerRoute,
} as any)
const WorkerTasksIndexRoute = WorkerTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerTasksTaskIdRoute = WorkerTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => WorkerRoute,
} as any)
const RetailerProductsProductIdEditRoute =
  RetailerProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => RetailerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/retailer': typeof RetailerRouteWithChildren
  '/retailer-application': typeof RetailerApplicationRoute
  '/search': typeof SearchRoute
  '/worker': typeof WorkerRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/retailer-applications': typeof AdminRetailerApplicationsRoute
  '/admin/retailers': typeof AdminRetailersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/retailer/dashboard': typeof RetailerDashboardRoute
  '/retailer/help': typeof RetailerHelpRoute
  '/retailer/inventory': typeof RetailerInventoryRoute
  '/retailer/login': typeof RetailerLoginRoute
  '/retailer/more': typeof RetailerMoreRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer/shop': typeof RetailerShopRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/worker/help': typeof WorkerHelpRoute
  '/worker/login': typeof WorkerLoginRoute
  '/worker/more': typeof WorkerMoreRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/delivery/$taskId': typeof AdminDeliveryTaskIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/retailers/$retailerId': typeof AdminRetailersRetailerIdRoute
  '/admin/shops/$shopId': typeof AdminShopsShopIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/retailer/orders/$orderId': typeof RetailerOrdersOrderIdRoute
  '/retailer/products/new': typeof RetailerProductsNewRoute
  '/worker/tasks/$taskId': typeof WorkerTasksTaskIdRoute
  '/retailer/orders/': typeof RetailerOrdersIndexRoute
  '/retailer/products/': typeof RetailerProductsIndexRoute
  '/worker/tasks/': typeof WorkerTasksIndexRoute
  '/retailer/products/$productId/edit': typeof RetailerProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/retailer': typeof RetailerRouteWithChildren
  '/retailer-application': typeof RetailerApplicationRoute
  '/search': typeof SearchRoute
  '/worker': typeof WorkerRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/retailer-applications': typeof AdminRetailerApplicationsRoute
  '/admin/retailers': typeof AdminRetailersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/retailer/dashboard': typeof RetailerDashboardRoute
  '/retailer/help': typeof RetailerHelpRoute
  '/retailer/inventory': typeof RetailerInventoryRoute
  '/retailer/login': typeof RetailerLoginRoute
  '/retailer/more': typeof RetailerMoreRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer/shop': typeof RetailerShopRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/worker/help': typeof WorkerHelpRoute
  '/worker/login': typeof WorkerLoginRoute
  '/worker/more': typeof WorkerMoreRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/orders': typeof OrdersIndexRoute
  '/admin/delivery/$taskId': typeof AdminDeliveryTaskIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/retailers/$retailerId': typeof AdminRetailersRetailerIdRoute
  '/admin/shops/$shopId': typeof AdminShopsShopIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/retailer/orders/$orderId': typeof RetailerOrdersOrderIdRoute
  '/retailer/products/new': typeof RetailerProductsNewRoute
  '/worker/tasks/$taskId': typeof WorkerTasksTaskIdRoute
  '/retailer/orders': typeof RetailerOrdersIndexRoute
  '/retailer/products': typeof RetailerProductsIndexRoute
  '/worker/tasks': typeof WorkerTasksIndexRoute
  '/retailer/products/$productId/edit': typeof RetailerProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/retailer': typeof RetailerRouteWithChildren
  '/retailer-application': typeof RetailerApplicationRoute
  '/search': typeof SearchRoute
  '/worker': typeof WorkerRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/retailer-applications': typeof AdminRetailerApplicationsRoute
  '/admin/retailers': typeof AdminRetailersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/retailer/dashboard': typeof RetailerDashboardRoute
  '/retailer/help': typeof RetailerHelpRoute
  '/retailer/inventory': typeof RetailerInventoryRoute
  '/retailer/login': typeof RetailerLoginRoute
  '/retailer/more': typeof RetailerMoreRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer/shop': typeof RetailerShopRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/worker/help': typeof WorkerHelpRoute
  '/worker/login': typeof WorkerLoginRoute
  '/worker/more': typeof WorkerMoreRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/delivery/$taskId': typeof AdminDeliveryTaskIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/retailers/$retailerId': typeof AdminRetailersRetailerIdRoute
  '/admin/shops/$shopId': typeof AdminShopsShopIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/retailer/orders/$orderId': typeof RetailerOrdersOrderIdRoute
  '/retailer/products/new': typeof RetailerProductsNewRoute
  '/worker/tasks/$taskId': typeof WorkerTasksTaskIdRoute
  '/retailer/orders/': typeof RetailerOrdersIndexRoute
  '/retailer/products/': typeof RetailerProductsIndexRoute
  '/worker/tasks/': typeof WorkerTasksIndexRoute
  '/retailer/products/$productId/edit': typeof RetailerProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/home'
    | '/map'
    | '/profile'
    | '/retailer'
    | '/retailer-application'
    | '/search'
    | '/worker'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/login'
    | '/admin/more'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/retailer-applications'
    | '/admin/retailers'
    | '/admin/settings'
    | '/admin/shops'
    | '/admin/users'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/retailer/dashboard'
    | '/retailer/help'
    | '/retailer/inventory'
    | '/retailer/login'
    | '/retailer/more'
    | '/retailer/profile'
    | '/retailer/shop'
    | '/shops/$shopId'
    | '/worker/dashboard'
    | '/worker/help'
    | '/worker/login'
    | '/worker/more'
    | '/worker/profile'
    | '/orders/'
    | '/admin/delivery/$taskId'
    | '/admin/orders/$orderId'
    | '/admin/products/$productId'
    | '/admin/retailers/$retailerId'
    | '/admin/shops/$shopId'
    | '/admin/users/$userId'
    | '/retailer/orders/$orderId'
    | '/retailer/products/new'
    | '/worker/tasks/$taskId'
    | '/retailer/orders/'
    | '/retailer/products/'
    | '/worker/tasks/'
    | '/retailer/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/home'
    | '/map'
    | '/profile'
    | '/retailer'
    | '/retailer-application'
    | '/search'
    | '/worker'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/login'
    | '/admin/more'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/retailer-applications'
    | '/admin/retailers'
    | '/admin/settings'
    | '/admin/shops'
    | '/admin/users'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/retailer/dashboard'
    | '/retailer/help'
    | '/retailer/inventory'
    | '/retailer/login'
    | '/retailer/more'
    | '/retailer/profile'
    | '/retailer/shop'
    | '/shops/$shopId'
    | '/worker/dashboard'
    | '/worker/help'
    | '/worker/login'
    | '/worker/more'
    | '/worker/profile'
    | '/orders'
    | '/admin/delivery/$taskId'
    | '/admin/orders/$orderId'
    | '/admin/products/$productId'
    | '/admin/retailers/$retailerId'
    | '/admin/shops/$shopId'
    | '/admin/users/$userId'
    | '/retailer/orders/$orderId'
    | '/retailer/products/new'
    | '/worker/tasks/$taskId'
    | '/retailer/orders'
    | '/retailer/products'
    | '/worker/tasks'
    | '/retailer/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/home'
    | '/map'
    | '/profile'
    | '/retailer'
    | '/retailer-application'
    | '/search'
    | '/worker'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/login'
    | '/admin/more'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/retailer-applications'
    | '/admin/retailers'
    | '/admin/settings'
    | '/admin/shops'
    | '/admin/users'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/retailer/dashboard'
    | '/retailer/help'
    | '/retailer/inventory'
    | '/retailer/login'
    | '/retailer/more'
    | '/retailer/profile'
    | '/retailer/shop'
    | '/shops/$shopId'
    | '/worker/dashboard'
    | '/worker/help'
    | '/worker/login'
    | '/worker/more'
    | '/worker/profile'
    | '/orders/'
    | '/admin/delivery/$taskId'
    | '/admin/orders/$orderId'
    | '/admin/products/$productId'
    | '/admin/retailers/$retailerId'
    | '/admin/shops/$shopId'
    | '/admin/users/$userId'
    | '/retailer/orders/$orderId'
    | '/retailer/products/new'
    | '/worker/tasks/$taskId'
    | '/retailer/orders/'
    | '/retailer/products/'
    | '/worker/tasks/'
    | '/retailer/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  HomeRoute: typeof HomeRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  RetailerRoute: typeof RetailerRouteWithChildren
  RetailerApplicationRoute: typeof RetailerApplicationRoute
  SearchRoute: typeof SearchRoute
  WorkerRoute: typeof WorkerRouteWithChildren
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ShopsShopIdRoute: typeof ShopsShopIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer': {
      id: '/retailer'
      path: '/retailer'
      fullPath: '/retailer'
      preLoaderRoute: typeof RetailerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer-application': {
      id: '/retailer-application'
      path: '/retailer-application'
      fullPath: '/retailer-application'
      preLoaderRoute: typeof RetailerApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/more': {
      id: '/admin/more'
      path: '/more'
      fullPath: '/admin/more'
      preLoaderRoute: typeof AdminMoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/retailer-applications': {
      id: '/admin/retailer-applications'
      path: '/retailer-applications'
      fullPath: '/admin/retailer-applications'
      preLoaderRoute: typeof AdminRetailerApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/retailers': {
      id: '/admin/retailers'
      path: '/retailers'
      fullPath: '/admin/retailers'
      preLoaderRoute: typeof AdminRetailersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer/dashboard': {
      id: '/retailer/dashboard'
      path: '/dashboard'
      fullPath: '/retailer/dashboard'
      preLoaderRoute: typeof RetailerDashboardRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/help': {
      id: '/retailer/help'
      path: '/help'
      fullPath: '/retailer/help'
      preLoaderRoute: typeof RetailerHelpRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/inventory': {
      id: '/retailer/inventory'
      path: '/inventory'
      fullPath: '/retailer/inventory'
      preLoaderRoute: typeof RetailerInventoryRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/login': {
      id: '/retailer/login'
      path: '/login'
      fullPath: '/retailer/login'
      preLoaderRoute: typeof RetailerLoginRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/more': {
      id: '/retailer/more'
      path: '/more'
      fullPath: '/retailer/more'
      preLoaderRoute: typeof RetailerMoreRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/profile': {
      id: '/retailer/profile'
      path: '/profile'
      fullPath: '/retailer/profile'
      preLoaderRoute: typeof RetailerProfileRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/shop': {
      id: '/retailer/shop'
      path: '/shop'
      fullPath: '/retailer/shop'
      preLoaderRoute: typeof RetailerShopRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/shops/$shopId': {
      id: '/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof ShopsShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/dashboard': {
      id: '/worker/dashboard'
      path: '/dashboard'
      fullPath: '/worker/dashboard'
      preLoaderRoute: typeof WorkerDashboardRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/help': {
      id: '/worker/help'
      path: '/help'
      fullPath: '/worker/help'
      preLoaderRoute: typeof WorkerHelpRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/login': {
      id: '/worker/login'
      path: '/login'
      fullPath: '/worker/login'
      preLoaderRoute: typeof WorkerLoginRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/more': {
      id: '/worker/more'
      path: '/more'
      fullPath: '/worker/more'
      preLoaderRoute: typeof WorkerMoreRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/profile': {
      id: '/worker/profile'
      path: '/profile'
      fullPath: '/worker/profile'
      preLoaderRoute: typeof WorkerProfileRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/admin/delivery/$taskId': {
      id: '/admin/delivery/$taskId'
      path: '/$taskId'
      fullPath: '/admin/delivery/$taskId'
      preLoaderRoute: typeof AdminDeliveryTaskIdRouteImport
      parentRoute: typeof AdminDeliveryRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/retailers/$retailerId': {
      id: '/admin/retailers/$retailerId'
      path: '/$retailerId'
      fullPath: '/admin/retailers/$retailerId'
      preLoaderRoute: typeof AdminRetailersRetailerIdRouteImport
      parentRoute: typeof AdminRetailersRoute
    }
    '/admin/shops/$shopId': {
      id: '/admin/shops/$shopId'
      path: '/$shopId'
      fullPath: '/admin/shops/$shopId'
      preLoaderRoute: typeof AdminShopsShopIdRouteImport
      parentRoute: typeof AdminShopsRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/retailer/orders/': {
      id: '/retailer/orders/'
      path: '/orders'
      fullPath: '/retailer/orders/'
      preLoaderRoute: typeof RetailerOrdersIndexRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/orders/$orderId': {
      id: '/retailer/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/retailer/orders/$orderId'
      preLoaderRoute: typeof RetailerOrdersOrderIdRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/products/': {
      id: '/retailer/products/'
      path: '/products'
      fullPath: '/retailer/products/'
      preLoaderRoute: typeof RetailerProductsIndexRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/products/new': {
      id: '/retailer/products/new'
      path: '/products/new'
      fullPath: '/retailer/products/new'
      preLoaderRoute: typeof RetailerProductsNewRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/worker/tasks/': {
      id: '/worker/tasks/'
      path: '/tasks'
      fullPath: '/worker/tasks/'
      preLoaderRoute: typeof WorkerTasksIndexRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/tasks/$taskId': {
      id: '/worker/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/worker/tasks/$taskId'
      preLoaderRoute: typeof WorkerTasksTaskIdRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/retailer/products/$productId/edit': {
      id: '/retailer/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/retailer/products/$productId/edit'
      preLoaderRoute: typeof RetailerProductsProductIdEditRouteImport
      parentRoute: typeof RetailerRoute
    }
  }
}

interface AdminDeliveryRouteChildren {
  AdminDeliveryTaskIdRoute: typeof AdminDeliveryTaskIdRoute
}

const AdminDeliveryRouteChildren: AdminDeliveryRouteChildren = {
  AdminDeliveryTaskIdRoute: AdminDeliveryTaskIdRoute,
}

const AdminDeliveryRouteWithChildren = AdminDeliveryRoute._addFileChildren(
  AdminDeliveryRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRetailersRouteChildren {
  AdminRetailersRetailerIdRoute: typeof AdminRetailersRetailerIdRoute
}

const AdminRetailersRouteChildren: AdminRetailersRouteChildren = {
  AdminRetailersRetailerIdRoute: AdminRetailersRetailerIdRoute,
}

const AdminRetailersRouteWithChildren = AdminRetailersRoute._addFileChildren(
  AdminRetailersRouteChildren,
)

interface AdminShopsRouteChildren {
  AdminShopsShopIdRoute: typeof AdminShopsShopIdRoute
}

const AdminShopsRouteChildren: AdminShopsRouteChildren = {
  AdminShopsShopIdRoute: AdminShopsShopIdRoute,
}

const AdminShopsRouteWithChildren = AdminShopsRoute._addFileChildren(
  AdminShopsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDeliveryRoute: typeof AdminDeliveryRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMoreRoute: typeof AdminMoreRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRetailerApplicationsRoute: typeof AdminRetailerApplicationsRoute
  AdminRetailersRoute: typeof AdminRetailersRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShopsRoute: typeof AdminShopsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDeliveryRoute: AdminDeliveryRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminMoreRoute: AdminMoreRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminProfileRoute: AdminProfileRoute,
  AdminRetailerApplicationsRoute: AdminRetailerApplicationsRoute,
  AdminRetailersRoute: AdminRetailersRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShopsRoute: AdminShopsRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RetailerRouteChildren {
  RetailerDashboardRoute: typeof RetailerDashboardRoute
  RetailerHelpRoute: typeof RetailerHelpRoute
  RetailerInventoryRoute: typeof RetailerInventoryRoute
  RetailerLoginRoute: typeof RetailerLoginRoute
  RetailerMoreRoute: typeof RetailerMoreRoute
  RetailerProfileRoute: typeof RetailerProfileRoute
  RetailerShopRoute: typeof RetailerShopRoute
  RetailerOrdersOrderIdRoute: typeof RetailerOrdersOrderIdRoute
  RetailerProductsNewRoute: typeof RetailerProductsNewRoute
  RetailerOrdersIndexRoute: typeof RetailerOrdersIndexRoute
  RetailerProductsIndexRoute: typeof RetailerProductsIndexRoute
  RetailerProductsProductIdEditRoute: typeof RetailerProductsProductIdEditRoute
}

const RetailerRouteChildren: RetailerRouteChildren = {
  RetailerDashboardRoute: RetailerDashboardRoute,
  RetailerHelpRoute: RetailerHelpRoute,
  RetailerInventoryRoute: RetailerInventoryRoute,
  RetailerLoginRoute: RetailerLoginRoute,
  RetailerMoreRoute: RetailerMoreRoute,
  RetailerProfileRoute: RetailerProfileRoute,
  RetailerShopRoute: RetailerShopRoute,
  RetailerOrdersOrderIdRoute: RetailerOrdersOrderIdRoute,
  RetailerProductsNewRoute: RetailerProductsNewRoute,
  RetailerOrdersIndexRoute: RetailerOrdersIndexRoute,
  RetailerProductsIndexRoute: RetailerProductsIndexRoute,
  RetailerProductsProductIdEditRoute: RetailerProductsProductIdEditRoute,
}

const RetailerRouteWithChildren = RetailerRoute._addFileChildren(
  RetailerRouteChildren,
)

interface WorkerRouteChildren {
  WorkerDashboardRoute: typeof WorkerDashboardRoute
  WorkerHelpRoute: typeof WorkerHelpRoute
  WorkerLoginRoute: typeof WorkerLoginRoute
  WorkerMoreRoute: typeof WorkerMoreRoute
  WorkerProfileRoute: typeof WorkerProfileRoute
  WorkerTasksTaskIdRoute: typeof WorkerTasksTaskIdRoute
  WorkerTasksIndexRoute: typeof WorkerTasksIndexRoute
}

const WorkerRouteChildren: WorkerRouteChildren = {
  WorkerDashboardRoute: WorkerDashboardRoute,
  WorkerHelpRoute: WorkerHelpRoute,
  WorkerLoginRoute: WorkerLoginRoute,
  WorkerMoreRoute: WorkerMoreRoute,
  WorkerProfileRoute: WorkerProfileRoute,
  WorkerTasksTaskIdRoute: WorkerTasksTaskIdRoute,
  WorkerTasksIndexRoute: WorkerTasksIndexRoute,
}

const WorkerRouteWithChildren =
  WorkerRoute._addFileChildren(WorkerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  HomeRoute: HomeRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  RetailerRoute: RetailerRouteWithChildren,
  RetailerApplicationRoute: RetailerApplicationRoute,
  SearchRoute: SearchRoute,
  WorkerRoute: WorkerRouteWithChildren,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ShopsShopIdRoute: ShopsShopIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
